### ISSUE TITLE
CERTABO_DATA_PATH not created by default

### ISSUE THREAD

**Issue by haklein** [haklein/certabo-playground#1]
Traceback (most recent call last):
  File "./certabo-lichess.py", line 49, in <module>
    os.path.join(CERTABO_DATA_PATH, "certabo-lichess.log"), backupCount=12
  File "/usr/lib/python3.7/logging/handlers.py", line 199, in __init__
    BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
  File "/usr/lib/python3.7/logging/handlers.py", line 54, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.7/logging/__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/.local/share/GUI/certabo-lichess.log'

**Comment by haklein** [comment]
certabo-lichess has been split into a separate repository, closing.
